version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./backend:/app
    working_dir: /app
    command: node server.js
    restart: always

  executor:
    build:
      context: ./executor
    image: code-executor
    command: tail -f /dev/null
    restart: always
